# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mschmit  <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/06/18 11:18:52 by mschmit           #+#    #+#              #
#    Updated: 2015/06/22 11:20:10 by mschmit          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT    = Dalek
SOURCES    = people.ml \
			doctor.ml \
			dalek.ml \
			main.ml
LIBS    =
include OCamlMakefile
